services:
  - type: web
    name: tscs-backend
    env: node
    plan: free
    rootDir: tscs-backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: EASYMAIL_API_URL
        value: https://easymail-nu.vercel.app/api/v1/emails
      - key: EASYMAIL_API_KEY
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        sync: false
      - key: BREVO_SENDER_NAME
        sync: false
      - key: EMAIL_FROM_NAME
        sync: false
      - key: SMS_API_URL
        sync: false
      - key: SMS_SERVICE_ID
        sync: false
      - key: SMS_SYSTEM_ID
        sync: false
